version: "3.9"

services:
  panel:
    image: pgcos:latest
    build: .
    command: ["panel"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
    environment:
      - TZ=Asia/Shanghai

  scheduler:
    image: pgcos:latest
    build: .
    command: ["scheduler"]
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
    environment:
      - TZ=Asia/Shanghai
